spring:
    jpa:
      show-sql: true
    datasource:
      url: jdbc:mysql://localhost:3306/bcsd # 본인의 환경에 맞게 수정한다.
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root # 본인의 환경에 맞게 수정한다.
      password: gkrdlsdlelql!! # 본인의 환경에 맞게 수정한다.
